name: Update gh-pages on new master
on:
  push:
    branches: master
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.x'
        include-prerelease: false
      
    - name: Publish .NET Core Project
      run: dotnet publish MyCoffeeNote.sln -c Release --nologo
      

      
    - name: Uploading files to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: MyCoffeeNote/MyCoffeeNote/bin/Release/net8.0/publish/wwwroot
