name: Update gh-pages on new master
on:
  push:
    branches: master
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.x'
        include-prerelease: false
      
    - name: Publish .NET Core Project
      run: dotnet publish MyCoffeeNote.sln -c Release --nologo
      
    # changes the base-tag in index.html from '/' to 'MyCoffeeNote' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to MyCoffeeNote
      run: sed -i 's/<base href="\/" \/>/<base href="\/MyCoffeeNote\/" \/>/g' MyCoffeeNote/MyCoffeeNote/bin/Release/net6.0/publish/wwwroot/index.html
	        
    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch MyCoffeeNote/MyCoffeeNote/bin/Release/net6.0/publish/wwwroot/.nojekyll
      
    - name: Uploading files to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: MyCoffeeNote/bin/Release/net6.0/publish/wwwroot
